language: php
php:
    - 5.5

before_script:
    - node --version
    - npm --version
    - phantomjs --version
    - nohup php -S localhost:8000 &
#    - nohup php -S localhost:8000 &>/dev/null &2>/dev/null

script:
    - npm install
    - node suite.js

